# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44a9c27af6bc609c5a0d8c13e870ce2120440fd240564781500d8d085b7e526a83b4789f3feeef205b447922cea5b5a12f4c4567df6afd2919dfebf7a54f2339

test:
  secret_key_base: c519e5b53fe052c6dcfc12255375cdbc6208c52b2049cc16cced4977aef596f824e6ff2fb2f85f139e109f8b4f42f4280518183ebd880e475fe962aa8ac3bf8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
